# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - install_netmhcpan: "true"
          - install_netmhcpan: "false"

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install tcsh
        run: sudo apt install -qq tcsh

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Show netMHCpan install script
        env:
          INSTALL_NETMHCPAN: ${{ matrix.install_netmhcpan }}
        run: if [[ "$INSTALL_NETMHCPAN" == true ]]; then cat scripts/install_netmhcpan.sh; fi

      - name: Install netMHCpan
        env:
          INSTALL_NETMHCPAN: ${{ matrix.install_netmhcpan }}
        run: if [[ "$INSTALL_NETMHCPAN" == true ]]; then ./scripts/install_netmhcpan.sh; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        env:
          INSTALL_NETMHCPAN: ${{ matrix.install_netmhcpan }}
        run: if [[ "$INSTALL_NETMHCPAN" == true ]]; then Rscript -e 'covr::codecov()'; fi

      - name: Lint
        env:
          INSTALL_NETMHCPAN: ${{ matrix.install_netmhcpan }}
        run: if [[ "$INSTALL_NETMHCPAN" == false ]]; then Rscript -e 'lintr::lint_package()'; fi

      - name: Install package
        run: Rscript -e 'remotes::install_github("tzina97/netMHCpan")'

      - name: Report
        run: Rscript -e 'netmhcpan::netmhcpan_report()'

      - name: Show your alleles
        run: Rscript -e 'netmhcpan::get_netmhcpan_alleles()'

      - name: Self-test
        env:
          INSTALL_NETMHCPAN: ${{ matrix.install_netmhcpan }}
        run: if [[ "$INSTALL_NETMHCPAN" == true ]]; then Rscript -e 'netmhcpan::netmhcpan_self_test()'; fi

